Output ren.gif

Require echo

Set Padding 0
Set Shell "bash"
Set FontSize 20
Set Width 1200
Set Height 600

Type@700ms "ren"
Sleep 500ms
Enter

Sleep 3000ms
Right

Sleep 700ms
Right

Sleep 700ms
Right

Sleep 1000ms
Type "c"

Sleep 1000ms
Type "x"

Sleep 1000ms
Type "r"

Sleep 1000ms
Left

Sleep 500ms
Left

Sleep 200ms
Left

Sleep 1200ms
Down

Sleep 1200ms
Down

Sleep 100ms
Enter

Sleep 5s
Type "q"